// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.3
// source: event.proto

/* eslint-disable */

export const protobufPackage = 'event';

export interface Event {
  id: string;
  name: string;
  start: Date | undefined;
  end: Date | undefined;
  description: string;
}

export interface ListReq {
  ids: string[];
  search?: string | undefined;
  paginate?: Paginate | undefined;
  orderBy?: Order | undefined;
}

export interface Paginate {
  page?: number | undefined;
  perPage?: number | undefined;
}

export interface Order {
  sort?: string | undefined;
  order?: string | undefined;
  nulls?: string | undefined;
}

export interface ListRes {
  list: Event[];
  totalCount: number;
}

export interface OneReq {
  id: string;
}

export interface OneRes {
  event: Event | undefined;
}

export interface EventGrpcService {
  list(request: ListReq): Promise<ListRes>;
  one(request: OneReq): Promise<OneRes>;
  create(request: Event): Promise<Event>;
  update(request: Event): Promise<Event>;
}
