// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.3
// source: notification.proto

/* eslint-disable */

export const protobufPackage = 'notification';

export interface Notification {
  id: string;
  title: string;
  body: string;
  from: string;
  to: string;
}

export interface ListReq {
  ids: string[];
  search?: string | undefined;
  paginate?: Paginate | undefined;
  orderBy?: Order | undefined;
}

export interface Paginate {
  page?: number | undefined;
  perPage?: number | undefined;
}

export interface Order {
  sort?: string | undefined;
  order?: string | undefined;
  nulls?: string | undefined;
}

export interface ListRes {
  list: Notification[];
  totalCount: number;
}

export interface OneReq {
  id: string;
}

export interface OneRes {
  notification: Notification | undefined;
}

export interface NotificationGrpcService {
  list(request: ListReq): Promise<ListRes>;
  one(request: OneReq): Promise<OneRes>;
  create(request: Notification): Promise<Notification>;
  update(request: Notification): Promise<Notification>;
}
