// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.27.3
// source: user.proto

/* eslint-disable */

export const protobufPackage = 'user';

export interface User {
  id: string;
  name: string;
}

export interface ListReq {
  ids: string[];
  search?: string | undefined;
  paginate?: Paginate | undefined;
  orderBy?: Order | undefined;
}

export interface Paginate {
  page?: number | undefined;
  perPage?: number | undefined;
}

export interface Order {
  sort?: string | undefined;
  order?: string | undefined;
  nulls?: string | undefined;
}

export interface ListRes {
  list: User[];
  totalCount: number;
}

export interface OneReq {
  id: string;
}

export interface OneRes {
  user: User | undefined;
}

export interface UserGrpcService {
  list(request: ListReq): Promise<ListRes>;
  one(request: OneReq): Promise<OneRes>;
  create(request: User): Promise<User>;
  update(request: User): Promise<User>;
}
